//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageGames.Torque.EngineData
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EngineData_Xbox_Debug
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EngineData_Xbox_Debug()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GarageGames.Torque.EngineData.EngineData_Xbox_Debug", typeof(EngineData_Xbox_Debug).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static byte[] Arial12
        {
            get
            {
                object obj = ResourceManager.GetObject("Arial12", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Arial14
        {
            get
            {
                object obj = ResourceManager.GetObject("Arial14", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Arial16
        {
            get
            {
                object obj = ResourceManager.GetObject("Arial16", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Arial18
        {
            get
            {
                object obj = ResourceManager.GetObject("Arial18", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Arial20
        {
            get
            {
                object obj = ResourceManager.GetObject("Arial20", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Arial22
        {
            get
            {
                object obj = ResourceManager.GetObject("Arial22", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] BlobShadow
        {
            get
            {
                object obj = ResourceManager.GetObject("BlobShadow", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] BloomCombineEffect
        {
            get
            {
                object obj = ResourceManager.GetObject("BloomCombineEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] BloomExtractEffect
        {
            get
            {
                object obj = ResourceManager.GetObject("BloomExtractEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] BlueFTexture
        {
            get
            {
                object obj = ResourceManager.GetObject("BlueFTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ClipMap
        {
            get
            {
                object obj = ResourceManager.GetObject("ClipMap", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ClipMapBlender
        {
            get
            {
                object obj = ResourceManager.GetObject("ClipMapBlender", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Courier12
        {
            get
            {
                object obj = ResourceManager.GetObject("Courier12", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Courier14
        {
            get
            {
                object obj = ResourceManager.GetObject("Courier14", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Courier16
        {
            get
            {
                object obj = ResourceManager.GetObject("Courier16", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Courier18
        {
            get
            {
                object obj = ResourceManager.GetObject("Courier18", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Courier20
        {
            get
            {
                object obj = ResourceManager.GetObject("Courier20", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Courier22
        {
            get
            {
                object obj = ResourceManager.GetObject("Courier22", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] CubemapEffect
        {
            get
            {
                object obj = ResourceManager.GetObject("CubemapEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] DetailEffect
        {
            get
            {
                object obj = ResourceManager.GetObject("DetailEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] DistanceFog
        {
            get
            {
                object obj = ResourceManager.GetObject("DistanceFog", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] GaussianBlurEffect
        {
            get
            {
                object obj = ResourceManager.GetObject("GaussianBlurEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] LightingEffect2D
        {
            get
            {
                object obj = ResourceManager.GetObject("LightingEffect2D", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] LightingEffect3D
        {
            get
            {
                object obj = ResourceManager.GetObject("LightingEffect3D", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] RefractionEffect
        {
            get
            {
                object obj = ResourceManager.GetObject("RefractionEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] SimpleEffect
        {
            get
            {
                object obj = ResourceManager.GetObject("SimpleEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ZPassEffect
        {
            get
            {
                object obj = ResourceManager.GetObject("ZPassEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
